name: Continuous Integration

on:
    pull_request:
        branches:
            - master

jobs:
    validate:
        name: Validate
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - uses: actions/cache@v4
              if: ${{ !env.ACT }}
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                  path: ./node_modules
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install Node Modules
              run: yarn install --network-timeout 100000

            - name: Validate and run tests
              run: yarn ci:test
