name: Continuous Integration

on:
    pull_request:
        branches:
            - master

jobs:
    automation-test-job:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x, 18.x] # Define Node.js versions to test against

        steps:
            # Step 1: Checkout the code (local version)
            - name: Checkout code
              uses: ./actions/checkout

            # Step 2: Set up Node.js based on matrix configuration (local version)
            - name: Set up Node.js ${{ matrix.node-version }}
              uses: ./actions/setup-node
              with:
                  node-version: ${{ matrix.node-version }}

            # Step 3: Cache node_modules (local version)
            - name: Cache node_modules
              uses: ./actions/cache
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            # Step 4: Install dependencies and run tests
            - name: Install dependencies and run tests
              run: |
                  npm install
                  npm run ci:test

            # Step 5: Upload test results (Optional, if you're saving artifacts)
            - name: Upload test results
              if: always()
              uses: ./actions/upload-artifact
              with:
                  name: test-results
                  path: test-results/
