name: Continuous Integration

on:
    pull_request:
        branches:
            - master

jobs:
    automation-test-job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "14"

            - name: npm install and test
              run: |
                  npm install
                  npm run ci:test
