name: Continuous Integration

on:
    pull_request:
        branches:
            - master

jobs:
    automation-test-job:
        runs-on: ubuntu-latest

        steps:
            # Menggunakan action checkout lokal
            - name: Checkout Repository
              uses: ./.github/actions/checkout

            # Menggunakan action setup-node lokal
            - name: Use Node.js
              uses: ./.github/actions/setup-node
              with:
                  node-version: "14"

            # Menjalankan npm install dan testing
            - name: npm install and test
              run: |
                  npm install
                  npm run ci:test
